version: 2.1

jobs:
  build:
    docker:
    - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    steps:
    - checkout

workflows:
  version: 2
  main:
    jobs:
      - build
