package setup

var artifacts = artifactSet{
	goVersion:       "1.17.1",
	etcdVersion:     "3.4.16",
	placematVersion: "2.0.5",
	coreOSVersion:   "2905.2.3",
	ctVersion:       "0.6.1",
	debPackages: []string{
		"git",
		"build-essential",
		"less",
		"wget",
		"systemd-container",
		"lldpd",
		"qemu",
		"qemu-kvm",
		"socat",
		"picocom",
		"swtpm",
		"cloud-utils",
		"bird2",
		"squid",
		"chrony",
		"dnsmasq",
		"xauth",
		"bash-completion",
		"dbus",
		"jq",
		"libgpgme11",
		"freeipmi-tools",
		"unzip",
		"skopeo",
		// required by building neco
		"fakeroot",
		// docker CE
		"docker-ce",
		"docker-ce-cli",
		"containerd.io",
	},
}
