name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: build
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      # Cloud Functions only supports a limited set of Go runtime versions.
      # This set may not contain the Go version we use in our development environment.
      # Therefore, we should run tests with both the Cloud Functions Go runtime version and our development environment Go version.
      # See `--runtime` options for `gcloud functions deploy` in `Makefile.*` to find the Cloud Functions runtime Go version we use.
      matrix:
        go-version: ["1.25"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - uses: flatt-security/setup-takumi-guard-golang@1c8aa7498f7f635fbd6ad6a0f436d03092b3502d # v1.1.0
        with:
          bot-id: "${{ vars.TAKUMI_GUARD_BOT_ID }}"
      - run: make check-generated
      - run: make lint
      - run: make test
      - run: make build
